# References
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'

services:
  mlflow:
    image: mlflow_xp:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./data:/mlflow"
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.sqlite
      ARTIFACT_ROOT: /mlflow/artifacts